name: 'SwiftUI Accessibility Bot'
description: 'Auto-applies LLM accessibility improvements to SwiftUI views and creates a PR.'
author: 'Pushpinder Pal Singh'

inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
  openai_model_name:
    description: 'OpenAI model name to use for generating accessibility improvements.'
    required: false
    default: 'gpt-4.1'
  process_changed_files_only:
    description: 'Whether to only process Swift files changed in the current commit. Defaults to false (process all SwiftUI files).'
    required: false
    default: 'false'

outputs:
  branch-name:
    description: 'Branch created for the PR'
  files-modified:
    description: 'Number of files modified'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'git-pull-request'
  color: 'red'
